# Kubernetes Deployment (k8s-manifests/backend-deployment.yaml)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crm-backend
  template:
    metadata:
      labels:
        app: crm-backend
    spec:
      containers:
      - name: crm-backend
        image: account-id.dkr.ecr.us-east-1.amazonaws.com/crm-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: crm-secrets
              key: db-url
