# Ansible Playbook (ansible/playbook.yml)
---
- hosts: jenkins
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
    - name: Install Kubernetes CLI
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.21.0/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true
